# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  terraform: circleci/terraform@2.0.1  

jobs:
  terraform-apply:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init
      - terraform/plan 
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  terraform:
    # Run the welcome/run job in its own container
    jobs:
      - terraform-apply
